<?= $this->doctype() ?>
<html lang="pt_br">
<head>


    <title>Serasa consumidor</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
    <link rel="stylesheet" href="/css/personal.css" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="UTF-8">
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top menu">
  <div class="container-fluid">

    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>
  </div>
</nav>

 <?= $this->content ?>



<div class="footer">
        2015 Serasa Experian. Todos os direitos reservados.<br/>
        SERASA S.A. com sede na alameda dos quinimuras, 187 Planalto Paulista. CEP 01068-900. São Paulo. SP.<br/>
        Inscrita no CPNJ/MF nº 62.173.620/00001-80 - IE Isenta www.serasaexperian.com.br

</div>
<div class="footer2">
           Certificado de autorização da Caixa 4-2936/2016. Promoção válida 08/11/16 à 27/03/17. Cada CPF concorrerá somente a um sorteio no valor de R$5.000,00 durante a promoção. Participação vinculada a abertura do cadastro positivo nos sites.<br/>
           e agências Serasa. Sorteio via extração da loteria Federal. Consulte as datas de sorteio, as condições de participação e regulamento completos no site www.serasaconsumidor.com.br/sorteiocadastropositivo.
</div>

</body>

<script src="/js/index.js"></script>
 <?= $this->inlineScript() ?>
</html>















