<?= $this->doctype() ?>
<html lang="pt_br">
<head>


    <title>Serasa consumidor</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
    <link rel="stylesheet" href="/css/personal.css" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="UTF-8">
</head>
<body>



<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand icon-se icon-se-logo" href="#"></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="#">COMO PARTICIPAR</a></li>
              <li><a href="#premios">PRÊMIOS E SORTEIOS</a></li>
              <li><a href="#ganhadores">GANHADORES</a></li>
              <li><a href="#regulamento">REGULAMENTO</a></li>
              <li><a href="#participar">PARTICIPE JÁ É GRÁTIS</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>




 <?= $this->content ?>



<div class="footer" id="regulamento">
        2015 Serasa Experian. Todos os direitos reservados.<br/>
        SERASA S.A. com sede na alameda dos quinimuras, 187 Planalto Paulista. CEP 01068-900. São Paulo. SP.<br/>
        Inscrita no CPNJ/MF nº 62.173.620/00001-80 - IE Isenta www.serasaexperian.com.br

</div>
<div class="footer2">
           Certificado de autorização da Caixa 4-2936/2016. Promoção válida 08/11/16 à 27/03/17. Cada CPF concorrerá somente a um sorteio no valor de R$5.000,00 durante a promoção. Participação vinculada a abertura do cadastro positivo nos sites.<br/>
           e agências Serasa. Sorteio via extração da loteria Federal. Consulte as datas de sorteio, as condições de participação e regulamento completos no site www.serasaconsumidor.com.br/sorteiocadastropositivo.
</div>

</body>

<script src="/js/index.js"></script>
 <?= $this->inlineScript() ?>
</html>















