<?php

namespace Application\Repositorio;
use Application\Entidade\Quiz;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository {


    /**
     * Metodo responsável por salvar as informações no banco de dados
     */
    public function doPersitir($objEntidade = null, $arrDados = []) {
        if (empty($objEntidade)) {
            $objEntidade = new Quiz();
        }


        $objEntidade->setName($arrDados['name']);
        $objEntidade->setDescription($arrDados['description']);
        $objEntidade->setCreatedAt($arrDados['create_at']);
        $objEntidade->setUpdatedAt(date('d/m/Y H:i:s'));

        try {
            $this->getEntityManager()
                ->persist($objEntidade);

            $this->getEntityManager()
                ->flush();
        } catch (\Exception $objException) {

            throw new \Exception($objException->getMessage(), 1);

        }

        return $objEntidade;

    }
}
