<!DOCTYPE html>
<!-- saved from url=(0051)http://getbootstrap.com/docs/4.0/examples/carousel/ -->
<html lang="pt-br">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Serasa">
    <!-- favicon -->
    <link rel="icon" href="https://www.serasaconsumidor.com.br/wp-content/themes/theme-serasaconsumidor/assets/img/favicon/favicon.ico">

    <title>Cadastro Positivo - Serasa</title>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="./bootstrap/bootstrap.min.css" rel="stylesheet">

    <link href="./assets/css/custom.css" rel="stylesheet">

</head>

<header>
    <div class="fixed-top menu-base">
        <section>
            <div class="row">

                <div class="col-lg-12">

                    <nav class="navbar navbar-expand-lg navbar-center navbar-light bg-light">
                        <a class="navbar-brand" href="#"></a>
                        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>


                        <div class="collapse navbar-collapse" id="navbarCollapse">
                            <ul class="nav navbar-nav navbar-right mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link page-scroll" href="#como-participar">COMO PARTICIPAR <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link page-scroll" href="#premios-sorteios">PRÊMIOS E SORTEIOS</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link page-scroll" href="#ganhadores">GANHADORES</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link page-scroll" href="#regulamento">REGULAMENTO</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-outline-serasa" href="#" role="button">PARTICIPE JÁ, É GRATIS!</a>
                                </li>
                            </ul>


                        </div>
                    </nav>
                </div>
            </div>
        </section>
    </div>
</header>


<section class="header-banner">
    <div class="container">
        <div class="row">

            <div class="col-lg-5 text-center zoom">
                <h2>
                    O SerasaConsumidor<br> ajuda a <b>pagar sua dívida!</b><br>
                    <span class="size-14">Abra seu Cadastro Positivo e concorra a</span>
                    <b>R$ <span class="valor">5.000,00</span></b>
                </h2>
                <a class="btn btn-primary" href="#" role="button">PARTICIPE JÁ, É GRATIS!</a>
                <br><br>

                <a href="#modal-cadastro-positivo" data-toggle="modal" data-target="#modal-cadastro-positivo">Saiba o que é o <u>CadastroPositivo</u></a>
            </div>
            <div class="col-lg-7">
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container">
        <div class="text-center" id="como-participar">
            <div class="row">


                <div class="col-lg-12">
                    <h2>Quer saber como abrir seu Cadastro Positivo e ainda concorrer a prêmios?</h2>
                </div>
                <div class="col-lg-4">
                    <i class="serasaconsumidor-icon bloco-participar-icon"></i>
                    <p><b>1.</b> Cadastre-se no <br><strong>SERASACONSUMIDOR</strong></p>

                </div>
                <!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <i class="cadastroposititvo-icon bloco-participar-icon"></i>
                    <p><b>2.</b> Abra o seu <br><strong>CADASTRO POSITIVO</strong></p>
                    <p><a class="btn btn-serasa" href="#" role="button">PARTICEPE JÁ, É GRÁTIS!</a></p>
                </div>
                <!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <i class="sorteio-icon bloco-participar-icon"></i>
                    <p>
                        <b>3.</b> Receba seu <b>número e data<br>
                            do sorteio</b> no seu email<br>
                        <span class="size-12">(Cada CPF participa de apenas um sorteio)</span>
                    </p>
                </div>
                <!-- /.col-lg-4 -->
            </div>
            <!-- /.row -->
        </div>
    </div>

</section>

<section class="bg-sorteios">

    <div id="premios-sorteios">
        <div class="row">

            <div class="col-md-8 participe1">
                <h4>Abrindo seu <b>Cadastro Positivo</b> você pode ganhar até <strong>R$ 5.000!</strong>
                </h4>
                <p>Cada CPF participa de apenas um sorteio. Assim que seu Cadastro Positivo for concluido, você vai receber por e-mail o seu número da sorte e a data do sorteio que você vai participar. Depois, é só torcer oara ser o ganhador.</p>
            </div>
            <div class="col-md-4 participe2">
                <i class="calendario-icon">12/10</i>
                <span class="span"> Próximo sorteio</span>
                <p><a class="btn btn-serasa" href="#" role="button">PARTICEPE JÁ, É GRATIS!</a></p>
            </div>

        </div>
    </div>
</section>

<section>
        <div id="ganhadores">
            <div class="row">
                <div class="col-md-8 ganhadores-box">
                    <h2>Ganhadores</h2>

                    <ul class="ganhadores" id="ganhadores-box">

                    </ul>
                </div>
                <div class="col-md-4 sorteios-box" >
                    <h2>Datas dos Sorteios</h2>

                    <ul class="datasorteios" id="datasorteios-box">

                    </ul>
                </div>
            </div>
        </div>
</section>



<footer>
    <div class="global-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>
                        2017 Serasa Experian. Todos os direitos reservados.<br> SERASA S. A. com sede na Alameda dos Quinimuras, 187, Planalto Paulista, CEP 04068-900, São Paulo, SP<br> Inscrita no CNPJ/MF n° 62.173.620/0001-80, IE Isenta. <a href="https://www.serasaexperian.com.br">www.serasaexperian.com.br</a>
                    </p>
                </div>
                <div class="col-md-6 text-right">
                    <p>
                        O serasaConsumidor se comunica diretamente com os gaanhadores da promoção e nunca<br> solicita nenhum pagamento para resgate de prêmio. Em caso de dúvida, entre em contato com<br> nossa Central de Atendimento Cadastro Positivo 0800 7766606.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-adress">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        Certificado de autorização da Caixa 4-2936/2016. Pormoção válida 08/11/16 á 27/03/16. Cada CPF concorrerá somente a um sorteio no valor de R$ 5.000 durante a promoção. Participação vinculada a abertura do Cadastro positivo nos sites<br> e agências Serasa. Sorteios via extração da Loteria Federal. Consulte as datas de sorteios, as condições de participação e o regulamento completos no site www.serasaconsumidor.com.br/sorteiocadastropositivo
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="modal fade" id="modal-cadastro-positivo" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cadastro Positivo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <iframe style="width: 100%" height="315" src="https://www.youtube.com/embed/UnMkKyZc5DA" frameborder="0" allowfullscreen=""></iframe>

            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="./node_modules/jquery/dist/jquery.min.js"></script>
<script src="./bootstrap/popper.min.js"></script>
<script src="./bootstrap/bootstrap.min.js"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="./assets/js/index.js"></script>


<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="25" style="font-weight:bold;font-size:25pt;font-family:Arial, Helvetica, Open Sans, sans-serif">500x500</text></svg></body>

</html>