<?php

namespace Api\Repositorio;

/**
 * WinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinnerRepository extends \Doctrine\ORM\EntityRepository
{
}
